project:
  type: website

website:
  title: "IS415_GAA"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu: 
          - text: "Hand-on Exercise2"
            href: "WeeklyExercise/week2/Handon2/handon2.html"
          - text: "Hand-on Exercise3"
            href: "WeeklyExercise/week3/Week3_handon.html"   
          - text: "Hand-on Exercise4"
            href: "WeeklyExercise/week4/Hands-on_Ex04/Handon_Ex04.html"  
          - text: "Hand-on Exercise6"
            href: "WeeklyExercise/week5/Hands-on_Ex05/Handon_Ex05.html"
          - text: "Hand-on Exercise6"
            href: "WeeklyExercise/week6/Hands-on_Ex06/Handon_Ex06.html"  
          - text: "Hand-on Exercise7"
            href: "WeeklyExercise/week7/Hands-on_Ex07/Handon_Ex07.html"  
          - text: "Hand-on Exercise9"
            href: "WeeklyExercise/week9/Hands-on_Ex09/Handon_Ex09.html"  
          - text: "Hand-on Exercise10"
            href: "WeeklyExercise/week10/Hands-on_Ex10/Handon_Ex10.html"
          - text: "Hand-on Exercise11"
            href: "WeeklyExercise/week11/Hands-on_Ex11/Handon_Ex11.html"  
          - text: "Hand-on Exercise12"
            href: "WeeklyExercise/week12/Hands-on_Ex12/Handon_Ex12.html" 
      - text: "In-Class Exercise"        
        menu: 
          - text: "In-Class Exercise 2"
            href: "WeeklyExercise/week2/In-Class_Ex02/InClassEx02.html"
          - text: "In-Class Exercise 3"
            href: "WeeklyExercise/week3/Week3_Inclass/InClassEx03.html"
          - text: "In-Class Exercise 4"
            href: "WeeklyExercise/week4/InClass_Ex04/InClass_Ex04.html"           
          - text: "In-Class Exercise 5"
            href: "WeeklyExercise/week5/InClass_Ex05/InClass_Ex05.html" 
          - text: "In-Class Exercise 6"
            href: "WeeklyExercise/week6/InClass_Ex06/InClass_Ex06.html" 
          - text: "In-Class Exercise7"
            href: "WeeklyExercise/week7/InClass_Ex07/InClass_Ex07.html" 
          - text: "In-Class Exercise9"
            href: "WeeklyExercise/week9/InClass_Ex09/InClass_Ex09.html" 
          - text: "In-Class Exercise10"
            href: "WeeklyExercise/week10/InClass_Ex10/InClass_Ex10.html"
          - text: "In-Class Exercise11"
            href: "WeeklyExercise/week11/InClass_Ex11/InClass_Ex11.html" 
          - text: "In-Class Exercise12"
            href: "WeeklyExercise/week12/InClass_Ex12/InClass_Ex12.html" 
      - text: "Takehome Exercise"
        menu: 
          - text: "Takehome_Exercise1"
            href: "Takehome_Exercise/Takehome_Exercise1/Takehome_Ex01.html"
          - text: "Takehome_Exercise2"
            href: "Takehome_Exercise/Takehome_Exercise2/Takehome_Ex02.html"
          - text: "Takehome_Exercise3"
            href: "Takehome_Exercise/Takehome_Exercise3/Takehome_Ex03.html"            

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
