---
title: "InClass_Ex07"
editor: visual
---

#### 

Launching the packages into R environment

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse,plotly)
```

#### Import shapefile into r environment

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_GDPPC <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
wm_q <- hunan_GDPPC %>% mutate(nb=st_contiguity(geometry),wt = st_weights(nb,style="W"), .before = 1)

```

#### Computing Global Moran'I

```{r}
moran <- global_moran(wm_q$GDPPC,wm_q$nb,wm_q$wt)

```

#### Performing Global Moran' test

```{r}
global_moran_test(wm_q$GDPPC,wm_q$nb,wm_q$wt)
```

```{r}
set.seed(1234)
```

```{r}
global_moran_perm(wm_q$GDPPC,wm_q$nb,wm_q$wt,nsim=99)
```

#### Computing local Moran's I

```{r}
lisa<- wm_q %>% mutate(local_moran=local_moran(GDPPC, nb,wt, nsim=99),.before=1) %>% unnest(local_moran)
lisa
```

```{r}
tmap_mode("plot")
tm_shape(lisa)+tm_fill("ii")+tm_borders(alpha=0.5)
```

```{r}
tmap_mode("plot")
tm_shape(lisa)+tm_fill("p_ii_sim")+tm_borders(alpha=0.5)
```

#### Visualize Local Moran's I

```{r}
lisa_sig <-lisa %>% filter(p_ii<0.05) 
tmap_mode("plot")
tm_shape(lisa)+tm_polygons()+tm_borders(alpha=0.5)+tm_shape(lisa_sig)+tm_fill("mean")+tm_borders(alpha=0.4)
```

#### Hot Spot and Clod Spot Analysis

```{r}
#IDEALLY we use local_gstar_perm to make sure the data is more stable 
HCSA <-wm_q %>% mutate(local_Gi=local_gstar_perm(GDPPC,nb,wt,nsim=99),.before=1)%>% unnest (local_Gi)
HCSA
```

```{r}
tmap_mode("plot")
tm_shape(HCSA)+tm_fill("p_sim")+tm_borders(alpha=0.5)
```

Creating a Time Series Cube

```{r}
#GDPPC_st <- spacetime(GDPPC,hunan,.loc_col = "County",.time_col="year")
```

```{r}
#GDPPC_nb <- GDPPC_st %>% activate("geometry") %>% mutate (nb=include_self(st_contiguity(geometry)),wt=st_weights(nb))%>% set_nbs("nb")%>% set_wts("wt")
```
