---
title: "InClass_Ex06"
editor: visual
---

#### Import shapefile into r environment

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse, knitr)
```

#### Import shapefile into r environment

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

#### Import csv file into r environment

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

#### Performing relational join

```{r}
#SF dataframe + tb dataframe
hunan_GDPPC <- left_join(hunan,hunan2012)%>%
  select(1:4, 7, 15)
#need to specify the joined field if the case different, R is very sensitive to uppercase/lowercase, need to make sure the column value are standardize
```

**Plotting a Choropleth map**

```{r}
tmap_mode("plot")
tm_shape(hunan_GDPPC)+
  tm_fill("GDPPC", 
          style = "quantile", 
          palette = "Blues",
          title = "GDP per district") +
  tm_layout(main.title = "Distribution of GDPPC by district",
            main.title.position = "center",
            main.title.size = 1.2,
            legend.height = 0.35, 
            legend.width = 0.25,
            frame = TRUE) +
  tm_borders(alpha = 0.4) +
  tm_compass(type="8star", size = 1) +
  tm_scale_bar() +
  tm_grid(alpha =0.2)
```

#### Computing Contiguity neighbours method

```{r}
cn_queen <- hunan_GDPPC %>% mutate(nb=st_contiguity(geometry),.before = 1)
```

```{r}
cn_roook <- hunan_GDPPC %>% mutate(nb=st_contiguity(geometry),queen=FALSE, .before = 1)
```

**Computing Contiguity Spatial Weights**

```{r}
wm_q <- hunan_GDPPC %>% mutate(nb=st_contiguity(geometry),wt = st_weights(nb), .before = 1)
```
