---
title: "InClass_Ex05"
editor: visual
---

```{r}
pacman::p_load(tidyverse,tmap,sf,sfdep)
```

```{r}
studyArea <- st_read(dsn = 'data',layer="study_area")%>% st_transform(crs=3829)
```

```{r}
stores <- st_read(dsn = 'data',layer="stores")%>% st_transform(crs=3829)
```

**Visualising the sf layers**

```{r}
tmap_mode("view")
tm_shape(studyArea)+tm_polygons()+tm_shape(stores)+tm_dots(col = "Name",size = 0.01,border.col="black",border.lwd=0.5
)+
  tm_view(set.zoom.limits = c(12,16))
```

**Local Colocation Quotients (LCLQ)**

Preparing nearest neighbours list

```{r}
nb <- include_self(st_knn(st_geometry(stores),6)
                   )
```

Computing kernel weights

```{r}
wt <- st_kernel_weights(nb,stores,"gaussian")
```

Preparing the vector list

```{r}
FamilyMart <- stores %>% filter(Name == "Family Mart")
A <- FamilyMart$Name
```

```{r}
SevenEleven <- stores %>% filter(Name=="7-Eleven")
B<- SevenEleven$Name
```

Computing LCLQ

```{r}
LCLQ <-local_colocation(A,B,nb,wt,49)
```

Joining output table

```{r}
LCLQ_stores <-cbind(stores,LCLQ)
```

Plotting LCLQ values

```{r}
tmap_mode("view")
tm_shape(studyArea) +
  tm_polygons() +
tm_shape(LCLQ_stores)+ 
  tm_dots(col = "X7.Eleven",
             size = 0.01,
             border.col = "black",
             border.lwd = 0.5) +
  tm_view(set.zoom.limits = c(12, 16))
```
